export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'; 
export const ADD_ERROR_TO_STORE = 'ADD_ERROR_TO_STORE';
export const CLEAR_ERROR_FROM_STORE = 'CLEAR_ERROR_FROM_STORE';
export const CHANGE_AUTH_STATUS_IN_STORE = 'CHANGE_AUTH_STATUS_IN_STORE';
export const ADD_AUTH_USER_DATA_TO_STORE ='ADD_AUTH_USER_DATA_TO_STORE';
export const CLEAR_AUTH_USER_DATA_FROM_STORE ='CLEAR_AUTH_USER_DATA_FROM_STORE';
export const LOADING_BEGIN_TO_STORE = 'LOADING_BEGIN_TO_STORE';
export const LOADING_END_TO_STORE = 'LOADING_END_TO_STORE';
export const ADD_SEARCH_LABEL_TO_STORE = 'ADD_SEARCH_LABEL_TO_STORE';
export const CHANGE_VISIBLE_WINDOW_NEW_EXERCISE_TO_STORE = 'CHANGE_VISIBLE_WINDOW_NEW_EXERCISE_TO_STORE';
export const ADD_GROUP_IMAGE_TO_STORE = 'ADD_GROUP_IMAGE_TO_STORE';
export const ADD_NEW_EXERCISE_TO_STORE = 'ADD_NEW_EXERCISE_TO_STORE';

export const DO_SIGN_IN = 'DO_SIGN_IN';
export const DO_REGISTER = 'DO_REGISTER';
export const DO_SIGN_OUT = 'DO_SIGN_OUT';
export const DO_ADD_NEW_EXERCISE = 'DO_ADD_NEW_EXERCISE';
